### ISSUE TITLE
error

### ISSUE THREAD

**Issue by devilxsam** [jainamoswal/BotStatus#7]
:::::::::::::::::::::: ⏲️ Action started successfully ⏲️ ::::::::::::::::::::::

Traceback (most recent call last):
  File "/home/runner/work/_actions/devilxsam/botstatus/main/main.py", line 118, in <module>
    json_data = client.loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/work/_actions/devilxsam/botstatus/main/main.py", line 76, in main
    async with client:
  File "/home/runner/.local/lib/python3.10/site-packages/telethon/client/auth.py", line 657, in __aenter__
    return await self.start()
  File "/home/runner/.local/lib/python3.10/site-packages/telethon/client/auth.py", line 165, in _start
    value = phone()
  File "/home/runner/.local/lib/python3.10/site-packages/telethon/client/auth.py", line 22, in <lambda>
    phone: typing.Callable[[], str] = lambda: input('Please enter your phone (or bot token): '),
EOFError: EOF when reading a line
/home/runner/work/_temp/b7da4cad-14e0-4611-8b88-b41d7db8e4[34](https://github.com/devilxsam/BotStatus/actions/runs/7943316535/job/21687542603#step:2:37).sh: line 1:  1660 Segmentation fault      (core dumped) python /home/runner/work/_actions/devilxsam/botstatus/main/main.py
Please enter your phone (or bot token): 
Error: Process completed with exit code 1[39](https://github.com/devilxsam/BotStatus/actions/runs/7943316535/job/21687542603#step:2:42).

**Comment by jainamoswal** [comment]
The error states that your session string is either invalid or revoked. 

retry with new session string.
